made output_directory optional

diff --git a/REST/gidl b/REST/gidl
--- a/REST/gidl
+++ b/REST/gidl
@@ -1,8 +1,8 @@
 #/usr/bin/sh
 
-if [ $# -ne 2 ]
+if [ $# -lt 1 ]
 then
-    echo "Usage: gidl <validation_xml_file> <output_directory>"
+    echo "Usage: gidl <validation_xml_file> [<output_directory>]"
     exit 1
 fi
 
@@ -10,13 +10,26 @@ file=$1
 output_directory=$2
 echo "Generating IDL:"$file
 echo "--------------"
-echo "lua $HOME/.luarocks/share/lua/5.3/idl_gen.lua $file $output_directory"
+if [ -f $HOME/.luarocks/share/lua/5.3/idl_gen.lua ]
+then
+    LUA_FILE="$HOME/.luarocks/share/lua/5.3/idl_gen.lua"
+elif [ -f /usr/local/share/lua/5.3/idl_gen.lua ]
+then
+    LUA_FILE="/usr/local/share/lua/5.3/idl_gen.lua"
+else
+    echo "File idl_gen not found"
+    exit 1
+fi
+echo "lua $LUA_FILE $file $output_directory"
 if [ "$output_directory" != "" ]
 then
     mkdir -p $output_directory
     cd $output_directory
+	lua $LUA_FILE ../$file $output_directory
+else
+	lua $LUA_FILE $file 
 fi
-lua $HOME/.luarocks/share/lua/5.3/idl_gen.lua ../$file $output_directory
+
 if [ $? -ne 0 ]
 then
 	exit 1;
diff --git a/orm/gtbl b/orm/gtbl
--- a/orm/gtbl
+++ b/orm/gtbl
@@ -1,8 +1,8 @@
 #/usr/bin/sh
 
-if [ $# -ne 3 ]
+if [ $# -lt 2 ]
 then
-	echo "Usage: gidl <tbl_spec_file> <common_ref_module> <output_directory>"
+	echo "Usage: gidl <tbl_spec_file> <common_ref_module> [<output_directory>]"
 	exit 1
 fi
 
@@ -11,13 +11,27 @@ common_ref_module=$2
 output_directory=$3
 echo "Generating TBL:"$file
 echo "--------------"
-echo "lua $HOME/.luarocks/share/lua/5.3/tblgen.lua $file $common_ref_module $output_directory"
+
+if [ -f $HOME/.luarocks/share/lua/5.3/tblgen.lua ]
+then
+	LUA_FILE="$HOME/.luarocks/share/lua/5.3/tblgen.lua"
+elif [ -f /usr/local/share/lua/5.3/tblgen.lua ]
+then
+	LUA_FILE="/usr/local/share/lua/5.3/tblgen.lua"
+else
+	echo "File tblgen.lua not found"
+	exit 1
+fi
+
+echo "lua $LUA_FILE $file $common_ref_module $output_directory"
 if [ "$output_directory" != "" ]
 then
 	mkdir -p $output_directory
 	cd $output_directory
+	lua $LUA_FILE ../$file $common_ref_module 
+else
+	lua $LUA_FILE $file $common_ref_module 
 fi
-lua $HOME/.luarocks/share/lua/5.3/tblgen.lua ../$file $common_ref_module 
 if [ $? -ne 0 ]
 then
 	exit 1;
diff --git a/schemarules/gval b/schemarules/gval
--- a/schemarules/gval
+++ b/schemarules/gval
@@ -1,8 +1,8 @@
 #/usr/bin/sh
 
-if [ $# -ne 3 ]
+if [ $# -lt 2 ]
 then
-	echo "Usage: gappingo <xml_file_name> <ref_common_module_name> <output_directory"
+	echo "Usage: gappingo <xml_file_name> <ref_common_module_name> [<output_directory>]"
 	exit 1
 fi
 
@@ -11,13 +11,25 @@ ref_common_module=$2
 output_directory=$3
 echo "Generating "$file
 echo "--------------"
-echo "lua $HOME/.luarocks/share/lua/5.3/generate_val.lua $file $ref_common_module $output_directory"
+if [ -f $HOME/.luarocks/share/lua/5.3/generate_val.lua ]
+then
+    LUA_FILE="$HOME/.luarocks/share/lua/5.3/generate_val.lua"
+elif [ -f /usr/local/share/lua/5.3/generate_val.lua ]
+then
+    LUA_FILE="/usr/local/share/lua/5.3/generate_val.lua"
+else
+    echo "File generate_val.lua not found"
+    exit 1
+fi
+echo "lua $LUA_FILE $file $ref_common_module $output_directory"
 if [ "$output_directory" != "" ]
 then
     mkdir -p $output_directory
     cd $output_directory
+    lua $LUA_FILE ../$file $ref_common_module $output_directory
+else
+	lua $LUA_FILE $file $ref_common_module
 fi
-lua $HOME/.luarocks/share/lua/5.3/generate_val.lua ../$file $ref_common_module $output_directory
 if [ $? -ne 0 ]
 then
 	exit 1;
